<?php require 'templates/header.phtml' ?>



<ul class="list-group">
    <div class="title text-center">
        <h1>CAMISETAS</h1>

    </div>
    <div class="flex" style=" display: flex;
    justify-content: center;
    flex-wrap: wrap;">
        <?php foreach ($camisetas as $camiseta) : ?>

            <div class="tarjetas ">
                <div class="card" style="width: 18rem;">
                    <img src="<?=$camiseta->imagen?>" class="card-img-top" alt="imagen de tarjeta">
                    <div class="card-body">
                        <h2><?= $camiseta->nombre_equipo ?></h2>
                        <h3><?= $camiseta->categoria_camiseta ?></h3>
                        <h6><?= $camiseta->tipo_camiseta ?></h6>
                        <p class="card-text">
                            Esta es la camiseta del <?= $camiseta->categoria_camiseta ?> <?= $camiseta->nombre_equipo ?> en la decada de los <?= $camiseta->numero_decada ?>s
                        </p>
                        <a href='camiseta/<?= $camiseta->id ?>' class="btn btn-primary">Ver mas</a>
                    </div>

                </div>
            </div>


        <?php endforeach ?>
    </div>
</ul>




<?php require 'templates/footer.phtml' ?>