<?php require 'templates/header.phtml' ?>


<?php foreach ($camiseta as $camiseta) : ?>
    <main class="container mt-5">
        <section class="noticia">
            <h1 class="mb-5"><?= $camiseta->nombre_equipo ?></h1>
            <p class="lead mt-3"><?= $camiseta->categoria_camiseta ?></p>
            <p>Decada de los <?= $camiseta->numero_decada ?>s</p>
            <div class="img">
                <img class="noticia-image" src="<?= $camiseta->imagen ?>" alt="...">

            </div>

        </section>
    </main>
    </ul>
    <?php endforeach ?>
    <?php
    if (isset($_SESSION['id_usuario'])){
    ?>

    
<form method='POST' action='edit/<?= $camiseta->id ?>'>

<?php require 'templates/form.admin.phtml' ?>;
        <button type="submit" class="btn btn-primary">Editar</button>
        </div>
</div>
</form>




<?php
    }
    ?>


<?php require 'templates/footer.phtml' ?>