<?php require 'templates/header.phtml' ?>



<ul class="list-group ">
    <div class="title text-center">
     <h1>DECADAS</h1>

    </div>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Excepturi itaque,
     blanditiis sint animi enim non nisi quisquam, officia tenetur dolores doloribus tempore impedit 
     quia repudiandae! Non accusamus quis dignissimos vero.</p>
    <?php foreach ($decadas as $decada) : ?>

        <li class="list-group-item list-group-item-action list-group-item-success d-flex justify-content-between">Decada de los:
            <div>

                <span class="badge bg-succes rounded-pill"> <a href='decada/<?=$decada->id_decada?>'><?= $decada->numero_decada ?>s</a></span>
            </div>

        </li>
    <?php endforeach ?>
</ul>




<?php require 'templates/footer.phtml' ?>