<?php require 'templates/header.phtml' ?>



<ul class="list-group ">
    <div class="title text-center">
     <h1>DECADAS</h1>

    </div>
    <p>Bienvenidos a la pagina Museo de Camisetas, en esta pagina encontrara camisetas de todas las decadas en la historia del futbol</p>
    <h4>Elija una decada para ver las camisetas de esa epoca</h4>
    <?php foreach ($decadas as $decada) : ?>

        <li class="list-group-item list-group-item-action  d-flex justify-content-between">Decada de los:
            <div>

                <span class="decada"> <a href='decada/<?=$decada->id_decada?>'><?= $decada->numero_decada ?>s</a></span>
            </div>

        </li>
    <?php endforeach ?>
</ul>




<?php require 'templates/footer.phtml' ?>