<div class="form-group">
        <label for="nombreCamiseta">Nombre del equipo </label>
        <input type="text" class="form-control" id="nombreCamiseta" name='nombreCamiseta' placeholder="Nombre del equipo o seleccion">
    </div>
    <div class="form-group">
        <label for="categoriaCamiseta">Categoria Camiseta</label>
        <input type="text" class="form-control" id="categoriaCamiseta" name='categoriaCamiseta' placeholder="Categoria Club o Seleccion">
    </div>
    <div class="form-group">
        <div class="form-group">
            <label for="tipoCamiseta">Tipo Camiseta</label>
            <input type="text" class="form-control" id="tipoCamiseta" name='tipoCamiseta' placeholder="Titular o Alternativa">
        </div>
        <div class="form-group">
            <label for="categoriaCamiseta">imagen Camiseta</label>
            <input type="text" class="form-control" id="imagen" name='imagen' placeholder="Pegar URL de la imagen">
        </div>
        <div class="form-group">
            <label for="idCamiseta">Decada</label>
            <select class="form-control" name='idCamiseta' id='idCamiseta'>
                <?php foreach ($decadas as $decada) : ?>
                    <option value='<?= $decada->id_decada ?>'><?= $decada->numero_decada ?></option>
                <?php endforeach ?>
            </select>